name: Emotion Palette Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.HOSTING }}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"
      - run: ssh-keyscan -p 22 poire.beget.tech >> "$HOME/.ssh/known_hosts"

      # Deploy
      - run: rsync --omit-dir-times -e "ssh -p 22 -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete . poire@poire.beget.tech:/home/p/poire/hereandnowcreation.art/public_html/palette
